// client/src/app/pages/home-page/home-page.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import './home-page.css';

interface User {
    photo_url: string;
    first_name: string;
}

interface HomePageProps {
    user: User | null;
}

const HomePage: React.FC<HomePageProps> = ({ user }) => {
    const navigate = useNavigate();

    const navigateTo = (path: string) => {
        navigate(path);
    };

    return (
        <div className="main-page-container">
            <div className="main-page-header">
                <div className="main-page-header-content">
                    <div className="main-page-header-content-avatar-border">
                        <div className="main-page-header-content-avatar">
                            {user?.photo_url}
                        </div>
                    </div>

                    <div className="main-page-header-content-data">
                        <div className="main-page-header-content-data-username">
                            {user?.first_name}
                        </div>
                        <div className="main-page-header-content-data-credits">
                            <div className="main-page-header-content-data-credits-1">
                                <div className="main-page-header-content-data-credits-1-icon"></div>
                                <div className="main-page-header-content-data-credits-1-value">
                                    100K
                                </div>
                            </div>
                            <div className="main-page-header-content-data-credits-1">
                                <div className="main-page-header-content-data-credits-2-icon"></div>
                                <div className="main-page-header-content-data-credits-1-value">
                                    152.5K
                                </div>
                                <div></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="main-page-menu">
                <div className="main-page-menu-buttons">
                    <div className="main-page-menu-button" onClick={() => navigateTo('in-game')}>
                        Играть
                    </div>
                    <div className="main-page-menu-button" onClick={() => navigateTo('leaderboard')}>
                        Лидерборд
                    </div>
                    <div className="main-page-menu-button">Рефералы</div>
                    <div className="main-page-menu-button">Настройки</div>
                </div>


            </div>
            <div className='main-page-hands-cards'>
                <div className='hands'>

                </div>
            </div>
            <div className="main-page-navbar">
                <div className="main-page-navbar-option menu">
                    <div className="main-page-navbar-option menu-icon"></div>
                    <h1>Меню</h1>
                </div>
                <div className="main-page-navbar-option quests">
                    <div className="main-page-navbar-option quests-icon"></div>
                    <h1>Квесты</h1>
                </div>
                <div className="main-page-navbar-option open">
                    <div className="main-page-navbar-option open-icon"></div>
                    <h1>Открытые</h1>
                </div>
                <div className="main-page-navbar-option new-game" onClick={() => navigateTo('new-game')}>
                    <div className="main-page-navbar-option new-game-icon"></div>
                    <h1>Создать игру</h1>
                </div>
            </div>

        </div>
    );
};

export default HomePage;

// client/src/app/home-page/home-page.component.ts
import { Component, Input } from '@angular/core';
import { Router, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [
    RouterOutlet,
  ],
  templateUrl: './home-page.component.html',
  styleUrl: './home-page.component.css'
})
export class HomePageComponent {
  @Input() user: any;

  constructor(private router: Router) {}

  ngOnInit() {
    console.log('User in NewGameComponent:', this.user); // Log user data in NewGameComponent
  }

  navigateTo(path: string) {
    this.router.navigate([path]);
  }
}

<div class="main-page-container">
    <div class="main-page-header">
        <div class="main-page-header-content">
            <div class="main-page-header-content-avatar-border">
                <div class="main-page-header-content-avatar">{{ user?.photo_url }}</div>
            </div>
            
            <div class="main-page-header-content-data">
                <div class="main-page-header-content-data-username">{{ user?.first_name }}</div>
                <div class="main-page-header-content-data-credits">
                    <div class="main-page-header-content-data-credits-1">
                        <div class="main-page-header-content-data-credits-1-icon"></div>
                        <div class="main-page-header-content-data-credits-1-value">100K</div>
                    </div>
                    <div class="main-page-header-content-data-credits-1">
                        <div class="main-page-header-content-data-credits-2-icon"></div>
                        <div class="main-page-header-content-data-credits-1-value">152.5K</div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    

    <div class="main-page-menu">
        <div class="main-page-menu-buttons">
            <div class="main-page-menu-button">Играть</div>
            <div class="main-page-menu-button">Лидерборд</div>
            <div class="main-page-menu-button">Рефералы</div>
            <div class="main-page-menu-button">Настройки</div>
        </div>
    </div>

    <div class="main-page-navbar">
        <div class="main-page-navbar-option menu">
            <div class="main-page-navbar-option menu-icon"></div>
            <h1>Меню</h1>
        </div>
        <div class="main-page-navbar-option quests">
            <div class="main-page-navbar-option quests-icon"></div>
            <h1>Квесты</h1>
        </div>
        <div class="main-page-navbar-option open">
            <div class="main-page-navbar-option open-icon"></div>
            <h1>Открытые</h1>
        </div>
        <div class="main-page-navbar-option new-game" (click)="navigateTo('create-game')">
            <div class="main-page-navbar-option new-game-icon"></div>
            <h1>Создать игру</h1>
        </div>
    </div>

    <router-outlet></router-outlet>
</div>


<div class="main-page-hands-bg"></div>


<link
        href="https://fonts.googleapis.com/css2?family=Cormorant+Infant:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">
